### ISSUE TITLE
Model support

### ISSUE THREAD

**Issue by raulrobi** [bestiejs/platform.js#100]
Hi everybody. I'm glad to take part of this site. I'm new, so sorry if I'm putting it in a incorrect area. I'm from Uruguay. I think platform.js it's a great plugin. I'm implementing it in a web site. However, I was testing it in a different models phone and I detect that there are some models that platform.js doesn't support, like Samsung Galaxy 5. 
Do you think to include them in the future?

Thank you so much!

**Comment by demoneaux** [comment]
Closed by d4b90cb6915d4e16fd802c7765e53e5338f71654.
