### ISSUE TITLE
Firefox for iOS incorrectly classified as "Firefox Mobile"

### ISSUE THREAD

**Issue by miketaylr** [bestiejs/platform.js#101]
This came up in https://bugzilla.mozilla.org/show_bug.cgi?id=1267084.

Chase.com thinks that FxiOS v3 is "Firefox Mobile v3" (likely Fennec?) and puts up an "old browser lol" message. It should probably be "Firefox for iOS" instead.

We should make sure the layout is identified as WebKit too.

**Comment by jdalton** [comment]
Hi @miketaylr!

Development on this project has slowed so a PR would go a long way.
No reasonable PR refused!

**Comment by miketaylr** [comment]
💃 
Absolutely, happy to work on a PR + tests.

**Comment by jdalton** [comment]
Moved to #103.
