### ISSUE TITLE
Show returned values in the docs.

### ISSUE THREAD

**Issue by rodrigograca31** [bestiejs/platform.js#104]
Hi!

I think the docs could be improved by showing what values a parameter could hold/return.

For example: I was trying to know what values `platform.name` would give me and I was not able to find that information.... More specifically, I wanted to know if it would "return" the value "Google Chrome" or "Chrome", and what other values it could give me.
[https://github.com/bestiejs/platform.js/blob/master/doc/README.md#platformname](https://github.com/bestiejs/platform.js/blob/master/doc/README.md#platformname)

I could help doing that but I don't have experience with `JSDoc-style comments`....

Thanks!

**Comment by rodrigograca31** [comment]
I've just noticed that the property `platform.os.family` has this information.....

**Comment by rodrigograca31** [comment]
@demoneaux I was talking about the documentation in itself (README.md) not the JS code.... Or you just need to regenerate the documentation from that JS code?

**Comment by demoneaux** [comment]
Yep @rodrigograca31, I'll regenerate the documentation from the JSDoc, together with the next release, probably some time next week.

**Comment by rodrigograca31** [comment]
@demoneaux Ok, great! :smile:
