### ISSUE TITLE
[Question] Is "Mobie" valid or a typo ?

### ISSUE THREAD

**Issue by pomeh** [bestiejs/platform.js#106]
Hello,

Just to be sure, I can see in [`test.js`](https://github.com/bestiejs/platform.js/blob/0870795f0c277a33cc2078a96e74434f89aa11d8/test/test.js#L159-L167) this content:

```
'Android Browser 1.0 (like Chrome 18.0.1025.308) on Samsung Galaxy S4 (Android 4.2.2)': {
  'ua' : 'Mozilla/5.0 (Linux; Android 4.2.2; en-au; SAMSUNG GT-I9500 Build/JDQ39) AppleWebKit/535.19 (KHTML, like Gecko) Version/1.0 Chrome/18.0.1025.308 Mobie Safari/535.19',
  'layout': 'WebKit',
  'manufacturer': 'Samsung',
  'name': 'Android Browser',
  'os': 'Android 4.2.2',
  'product': 'Galaxy S4',
  'version': '1.0'
},
```

The user agent contains `Mobie`. Is it normal or is it a typo and should be `Mobile` instead ? I guess it's ok but I can't find anything to confirm this.

Thanks for your answer,

Romain

**Comment by jdalton** [comment]
It's a typo :)
