### ISSUE TITLE
Windows Server reports version within 'platform.os.family'

### ISSUE THREAD

**Issue by jpuffer** [bestiejs/platform.js#107]
Users on Windows Server are getting the following string in `platform.os.family`:
`Windows Server 2008 R2 / 7`

Expected behavior would be to only see `Windows Server` there.

**Comment by jdalton** [comment]
This is by design and based on Windows [platform tokens](https://en.wikipedia.org/wiki/List_of_Microsoft_Windows_versions).

**Comment by jpuffer** [comment]
What about the `/ 7` which is duplicated in `os.version`: `7`?  In the least, that part appears to be erroneous.

**Comment by jdalton** [comment]
The token `NT 6.1` is valid for Windows 7 and Server 2008 R2.
