### ISSUE TITLE
new stable version release

### ISSUE THREAD

**Issue by arpu** [bestiejs/platform.js#108]
do you plan to release a new stable version?

**Comment by sakulstra** [comment]
Would als be interested in this! We desperately need a release which supports meteor ;)

**Comment by demoneaux** [comment]
Yep, we probably need a new release, but I think I'll try to include fix #85 first.

**Comment by demoneaux** [comment]
We've just bumped to [1.3.2](https://github.com/bestiejs/platform.js/releases/tag/1.3.2), which has been released on npm too!
