### ISSUE TITLE
Cannot read property '0' of null

### ISSUE THREAD

**Issue by sakulstra** [bestiejs/platform.js#109]
Hello, when trying to use this library inside meteor I get the following error:
`platform.js:734 Uncaught TypeError: Cannot read property '0' of null` as reported here: https://github.com/meteor/meteor/issues/7839

Would the solution at the end of the ticket be accepted, or do you guys have another suggestion?

Thanks for your efforts,
regards,
lukas

**Comment by jdalton** [comment]
Hi @sakulstra!

Sure, a PR would be great!

**Comment by jdalton** [comment]
Moved to #111.
