### ISSUE TITLE
Breaking change was introduced in 1.3.1 ~> 1.3.2 patch release

### ISSUE THREAD

**Issue by mbixby** [bestiejs/platform.js#112]
['Place more common consumer Windows OS names before Windows Server names'](https://github.com/bestiejs/platform.js/commit/6d17ca2f418db743afd791786cde40ffafbf70ea)  changed titles for some versions of Windows (e.g. `'Server 2008 R2 / 7` ~> `7 / Server 2008 R2`). This was public API and some people were using it for comparisons (based on other tickets here).

The previous values should be reverted in the next patch release (1.3.3), breaking change should increment major version.

**Comment by demoneaux** [comment]
Seems like there's another breaking change in https://github.com/bestiejs/platform.js/commit/d6e64f19ae6d1c4ade0c1e7ccadc5ec6ba4aa0fa. I'll try to do a patch release tomorrow. Sorry for not taking SemVer into consideration, I guess I'll shift those into v2.0.

**Comment by demoneaux** [comment]
I've tagged [v1.3.3](https://github.com/bestiejs/platform.js/releases/tag/1.3.3), which has commit 3d23631556541d75cae69f89034f920f242f8be5, reverting the changes from 6d17ca2f418db743afd791786cde40ffafbf70ea.
