### ISSUE TITLE
Version number in file

### ISSUE THREAD

**Issue by SwintDC** [bestiejs/platform.js#121]
It would be an enhancement if the version number was explicitly mentioned on top of the source file, like in the example below:
```
/*!
 * Platform.js v1.3.3 <https://mths.be/platform>
 * Copyright 2014-2016 Benjamin Tan <https://demoneaux.github.io/>
 * Copyright 2011-2013 John-David Dalton <http://allyoucanleet.com/>
 * Available under MIT license <https://mths.be/mit>
 */
```

**Comment by jdalton** [comment]
Hi @SwintDC!

I'd rather add a `VERSION` property.

**Comment by jdalton** [comment]
@SwintDC  Would you be up for creating a pull request?
