### ISSUE TITLE
React native detection

### ISSUE THREAD

**Issue by bilby91** [bestiejs/platform.js#122]
Hello,

I'm experiencing some errors when twilio-chat uses the library on a react-native application (iOS and React Native Debugger). 

`undefined is not an object (evaluating '(typeof navigator!=='undefined'?navigator.userAgent:'web').substring')`

Have anyone used the library in a react-native application ?

Thanks!

**Comment by bilby91** [comment]
@jdalton Hi! Any plans for a new release ? `twilio-chat` resolved their issues and the only thing that is blocking it from running on react-native is `platform.js`. #123 solves the problem.

Thanks!

**Comment by jdalton** [comment]
Ah yap. I'm no longer lead on this so defer most to @demoneaux but I can push it out.

**Comment by bilby91** [comment]
@jdalton Thanks for the quick reply! @demoneaux do you think you can push a new version ?

**Comment by jdalton** [comment]
Bumped!

**Comment by bilby91** [comment]
@jdalton Awesome! Thanks
