### ISSUE TITLE
Node detection broken in version 1.3.4

### ISSUE THREAD

**Issue by pubkey** [bestiejs/platform.js#125]
I updated to version `1.3.4` and it seems that the following basic behavior does not work anymore.

example code:
```js
var platform = require('platform');

console.log(platform.name);
console.log(platform.version);
```

output:

```
null
null
```

Output of the same code with platform version `1.3.3`:
```
Node.js
7.8.0
```

Nodejs-version:  `7.6.0`

**Comment by jdalton** [comment]
To say that nothing works is an exaggeration. More accurately the Node detection doesn't work.

**Comment by pubkey** [comment]
Yes you are right. I'm sorry for that.
Edited the issue

**Comment by d3x0r** [comment]
https://github.com/bestiejs/platform.js/commit/1218b048d6895c1f6da447d57ebb2c6239384e48
breaks this.
```
versions is :  { http_parser: '2.7.0',
  node: '7.9.0',
  v8: '5.5.372.43',
  uv: '1.11.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '51',
  openssl: '1.0.2k',
  icu: '58.2',
  unicode: '9.0',
  cldr: '30.0.3',
  tz: '2016j' }
```
no nw or electron so it needs an 'else { } ' do the same old thing... (which is the else of if( typeof data.versions is object) )

**Comment by jdalton** [comment]
Moved to #130.
