### ISSUE TITLE
Chrome on macOs appearing as Node.js

### ISSUE THREAD

**Issue by marcelotmagalhaes** [bestiejs/platform.js#128]
Hello, I've just installed platform on my node.js test site and made a request to my test api with platform running. But the info returned are not from the browser, am I doing something wrong here?
I'm running the tests on localhost (both the site and the api).

EDIT: I'm using the 1.3.3 version, 1.3.4 is returning all nulls...

**Logs:**
console.log(platform.name);
console.log(platform.version);
console.log(platform.layout);
console.log(platform.os); 
console.log(platform.description); 

**Returned data:**
Node.js
6.9.2
null
{ architecture: 64,
  family: 'Darwin',
  version: null,
  toString: [Function: toString] }
Node.js 6.9.2 on Darwin 64-bit

**Comment by jdalton** [comment]
What browser are you logging `console.log(platform.name)` in ?

**Comment by marcelotmagalhaes** [comment]
The section **returned data** are the values for the logs above. 
The **platform.name** returns **Node.js**, but my browser is **Chrome 57.0.2987.133 (64-bit)** on **macOs 10.12.4**.

**Comment by jdalton** [comment]
Are you logging them in the browser or on the server?

**Comment by marcelotmagalhaes** [comment]
I'm logging on the api server that receives the requests.

**Comment by jdalton** [comment]
Since you're using platform on the server it's picking up the server as the platform.
Related to #125.
