### ISSUE TITLE
Headless Chorme is detected as Safari

### ISSUE THREAD

**Issue by wereHamster** [bestiejs/platform.js#132]
UA string: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/60.0.3107.4 Safari/537.36

Result of parse() is:

```javascript
{
  description: 'Safari 7.x on Linux 64-bit',
  layout: 'WebKit',
  manufacturer: null,
  name: 'Safari',
  prerelease: null,
  product: null,
  ua: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/60.0.3107.4 Safari/537.36',
  version: '7.x',
  os: {
    architecture: 64,
    family: 'Linux',
    version: null,
  },
}
```

Tracked down because [wdio-visual-regression-service] uses this library to detect the browser name, and it ends up as `Safari`.

[wdio-visual-regression-service]: https://github.com/zinserjan/wdio-visual-regression-service

**Comment by jdalton** [comment]
Thank you @moduleType! Would you be open to a PR?

**Comment by kevinpthorne** [comment]
Are there plans to merge @chiefcll's fixes? It has been awhile...
