### ISSUE TITLE
I am getting null all values when started server!

### ISSUE THREAD

**Issue by nikunjdnp** [bestiejs/platform.js#137]
Hi,
Here,I put code snippet where i get null value of plateform detail.

`var platform = require('platform');`

`var source = req.headers['user-agent'], ua = useragent.parse(source);`
`var info = platform.parse(ua.source);`
`let machineInfo = {
        "browser-name": ua.browser,
        "browser-version": ua.version,
        "osType": info.os.family,
        "osVersion": info.os.version 
    };`

resultant output is : 

`{ description: null,
  layout: null,
  manufacturer: null,
  name: null,
  prerelease: null,
  product: null,
  ua: null,
  version: null,
  os: 
   { architecture: null,
     family: null,
     version: null,
     toString: [Function: toString] },
  parse: [Function: parse],
  toString: [Function: toStringPlatform] }`

please help me!

**Comment by sailajagajulamsg** [comment]
Same here!!

**Comment by jdalton** [comment]
Dup of #130.

**Comment by nikunjdnp** [comment]
May I have information that when will i get? I mean version number!
