### ISSUE TITLE
Detection of iOS and Android WebView

### ISSUE THREAD

**Issue by AntonioSpalluto** [bestiejs/platform.js#138]
Hi all,

Is there any way to detect if the browser is loaded by the app WebView (iOS or Android) instead of the normal browser?

Thanks

**Comment by jdalton** [comment]
Hi @AntonioSpalluto!

Somtimes. It depends on the browser and its version. The go-to to check would be their UA string. If that's not enough then folks start looking for features or properties to detect.

**Comment by amorenew** [comment]
By passing user agent from webview you can detect if it is hybrid app
'web-mobile-android' so you can hide menu in that case or whatever you want by just user agent
