### ISSUE TITLE
Just food for thought.

### ISSUE THREAD

**Issue by WHBitbucket** [bestiejs/platform.js#140]
I do find as great as this library is, its missing some general features which I think are quite important.

The first (unless Im missing something) is the fact that you dont show the actual version detected.

Its nice to know its IE whatever but I actually need to know what version that IE is trying to be.

Currently Im having to use two libraries. I could do some Regex on parts of yours but its seems like something it should have.

This is an example as to what (Im guessing) most are using in some form. But notice in my case the two libraries.

SomePage.htm

<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta charset="utf-8" />

    <title>Browser</title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta name="robots" content="noindex,nofollow">

</head>
<body>
        <style>

            * {
                margin: 0;
                padding: 0;
            }

            html {
                font-family: sans-serif;
                line-height: 1.15;
                -webkit-text-size-adjust: 100%;
                -ms-text-size-adjust: 100%;
                -ms-overflow-style: scrollbar;
                -webkit-tap-highlight-color: transparent;
            }

            body {
                font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
                font-size: 100%;
                font-weight: normal;
                line-height: 1.5;
                text-align: center;
            }

            p {
                padding: 10px 0 10px 0;
                text-align: center;
                font-size: 100%;
                line-height: 1.5;
            }

            h1 {
                margin-top: 0;
                margin-bottom: 10px;
                color: #cc0000;
                font-size: 150%;
                font-weight: 400;
                text-align: center;
            }

            img {
                border: 0 solid;
            }

            hr {
                color: #fff;
                background: transparent;
                margin: 0 0 0.75em 0;
                padding: 0 0 0.67857em 0;
                border: 0;
                border-bottom: 1px #eeeeee solid;
            }

            th,
            td {
                line-height: 1.5em;
                vertical-align: top;
                padding: 2px 10px;
                text-align:left;
            }

                th.nowrap,
                td.nowrap {
                    white-space: nowrap;
                }

            * html .container {
                width: expression( document.body.clientWidth > 799 ? "800px" : "auto" );
            }

            .container {
                max-width: 50.000em;
                margin: 0 auto;
            }

                .container .container-content {
                    margin: 10px 10px 0px 10px;
                    padding-top: 10px;
                    padding-bottom: 10px;
                }

            .header {
                text-align: left;
            }

            .main {
                background: #e9ecef;
                -webkit-border-radius: 3px;
                -moz-border-radius: 3px;
                border-radius: 3px;
                text-align: left;
            }

                .main .main-content {
                    padding: 20px 20px 20px 20px;
                }

            .footer {

            }

        </style>

        <div class="container">
            <div class="container-content">

                <div class="header">
                    <img src="/some-logo.png" alt="SomeLogo" class="some-logo">
                </div>

                <hr />

                <div class="main">
                    <div class="main-content">
                        <h1>Sorry but you appear to be using an older browser or device that is incompatible with Blah Blah.</h1>

                        <p>
                            Blah Blah is designed for the best user experience which requires a modern browser.
                            Please contact your IT department to upgrade your browser or device to improve your experience
                            and security.
                        </p>

                        <br />

                        <table>
                            <tr>
                                <th class="nowrap">Browser Name</th>
                                <td id="browser-name"></td>
                            </tr>
                            <tr>
                                <th class="nowrap">Actual Browser Version</th>
                                <td id="actual-browser-version"></td>
                            </tr>
                            <tr>
                                <th class="nowrap">Detected Browser Version</th>
                                <td id="detected-browser-version"></td>
                            </tr>
                            <tr>
                                <th class="nowrap">Browser Layout</th>
                                <td id="browser-layout"></td>
                            </tr>
                            <tr>
                                <th class="nowrap">Product</th>
                                <td id="product"></td>
                            </tr>
                            <tr>
                                <th class="nowrap">manufacturer</th>
                                <td id="manufacturer"></td>
                            </tr>
                            <tr>
                                <th class="nowrap">Browser Description</th>
                                <td id="browser-description"></td>
                            </tr>
                            <tr>
                                <th class="nowrap">Operating System</th>
                                <td id="operating-system"></td>
                            </tr>
                            <tr>
                                <th class="nowrap">User Agent</th>
                                <td id="user-agent"></td>
                            </tr>
                        </table>

                   </div>
                </div>
            </div>
        </div>

    <script src="/Scripts/bowser.js"></script>
    <script src="/Scripts/platform.js"></script>

    <script>
            (function () {

                

                var browserNameSpan            = document.createElement("span");
                var actualBrowserVersionSpan   = document.createElement("span");
                var detectedBrowserVersionSpan = document.createElement("span");
                var browserLayoutSpan          = document.createElement("span");
                var productSpan                = document.createElement("span");
                var manufacturerSpan           = document.createElement("span");
                var browserDescriptionSpan     = document.createElement("span");
                var operatingSystemSpan        = document.createElement("span");
                var browserUserAgentSpan       = document.createElement("span");

                browserNameSpan.innerHTML            = platform.name;
                actualBrowserVersionSpan.innerHTML   = platform.version;
                detectedBrowserVersionSpan.innerHTML = bowser.version;
                browserLayoutSpan.innerHTML          = platform.layout;
                productSpan.innerHTML                = platform.product;
                manufacturerSpan.innerHTML           = platform.manufacturer;
                browserDescriptionSpan.innerHTML     = platform.description;
                operatingSystemSpan.innerHTML        = platform.os;
                browserUserAgentSpan.innerHTML       = window.navigator.userAgent;

                document.getElementById("browser-name").appendChild(browserNameSpan);
                document.getElementById("actual-browser-version").appendChild(actualBrowserVersionSpan);
                document.getElementById("detected-browser-version").appendChild(detectedBrowserVersionSpan);
                document.getElementById("browser-layout").appendChild(browserLayoutSpan);
                document.getElementById("product").appendChild(productSpan);
                document.getElementById("manufacturer").appendChild(manufacturerSpan);
                document.getElementById("browser-description").appendChild(browserDescriptionSpan);
                document.getElementById("operating-system").appendChild(operatingSystemSpan);
                document.getElementById("user-agent").appendChild(browserUserAgentSpan);

            })();
    </script>

</body>
</html>

------------------------------------------------------------------------------------------------------

I like the fact that in bowser.js I can do this.

<script>

            (function () {
                if (bowser.msie && bowser.version < 10) {
                    window.location.replace("/SomePage.htm");
                }
            })();

        </script>

https://github.com/lancedikson/bowser

**Comment by jdalton** [comment]
Hi @WHBitbucket!

This isn't really intended as a sniffing or detection lib to toggle features.
It's more for reporting purposes.

**Comment by bnjmnt4n** [comment]
> Its nice to know its IE whatever but I actually need to know what version that IE is trying to be.

`platform.version` does report the version of the browser, so it would be great if you could clarify what this means.

As mentioned though, for feature detection, you should probably use another library such as [Modernizr](https://modernizr.com) as Platform.js is more for providing detailed information on the platform.

**Comment by WHBitbucket** [comment]
It quite a while ago I wrote this but from memory the main "issue" was platform.version does correctly tell you the actual browser. It doesn't inform you if the browser is pretending to be a different version. I think in this use case (from memory) it was because IE 10 on an intranet pretends its IE 8. platform.version reports IE 10 which is correct. It would be nice to maybe have an additional platform.pretending.to.be.version or suchlike.
