### ISSUE TITLE
Add support IE8

### ISSUE THREAD

**Issue by knalbandianbrightgrove** [bestiejs/platform.js#143]
In Node.js mode get an error in IE8

`getters & setters can not be defined on this javscript engine`

Any workaround how it can be solved?

**Comment by jdalton** [comment]
Hi @knalbandianbrightgrove!

IE8 is way pasted dead. We're not supporting it. Good luck.

**Comment by knalbandianbrightgrove** [comment]
@jdalton 

Sorry for disturb, but why you don't support it if the library purpose is detect platform?!

A lot of users still use IE8 mode through IE compatibility,

**Comment by jdalton** [comment]
We can't support all-the-things so we make a cut at no longer supported platforms. IE8 hasn't been supported by Microsoft for years now so it didn't make the cut.

**Comment by bnjmnt4n** [comment]
> getters & setters can not be defined on this javscript engine

Also, taking a look at this I don't believe this is an issue with Platform.js as we don't use getters and setters. Although we don't actively test and support IE 8, I do recall the script working fine on IE 8 a few months ago.
