### ISSUE TITLE
 'define' is not defined  no-undef bug

### ISSUE THREAD

**Issue by amorenew** [bestiejs/platform.js#144]
I got this error when I run
any help?
Line 1204:  'define' is not defined  no-undef
Line 1204:  'define' is not defined  no-undef
Line 1211:  'define' is not defined  no-undef

**Comment by jdalton** [comment]
Hi @amorenew!

It looks like you are running your linter over 3rd-party code. You should tweak your include/exclude rules.

**Comment by amorenew** [comment]
@jdalton 
I found a simple fix
`/*global define */`
could you just add it to the following code
```
  // Some AMD build optimizers, like r.js, check for condition patterns like the following:
  /*global define */
  if (typeof define == 'function' && typeof define.amd == 'object' && define.amd) {

```

**Comment by jdalton** [comment]
I'm not into linting my project to others standards.
You should learn to use and configure your tools correctly.
