### ISSUE TITLE
Copyright mention points to no longer valid site

### ISSUE THREAD

**Issue by NazarenoL** [bestiejs/platform.js#152]
In platform.js

` * Copyright 2011-2013 John-David Dalton <http://allyoucanleet.com/>`

This website now points through a chain of redirects and ends on a ads parking website. 

A fun implication of this is that, as this domain was [blocked](https://developers.intern.facebook.com/tools/debug/sharing/?q=http%3A%2F%2Fallyoucanleet.com) by Facebook, [Instant Games](https://developers.facebook.com/docs/games/instant-games) uploaded containing this line will get automatically rejected.

**Comment by jdalton** [comment]
@NazarenoL You can just leave the name and remove the site.

**Comment by jdalton** [comment]
Closed by #153
