### ISSUE TITLE
Kai OS support

### ISSUE THREAD

**Issue by bartoszboruta** [bestiejs/platform.js#160]
It seems like this package does not recognize "kai os" systems.

**Comment by jdalton** [comment]
Hi @bartoszboruta!

Is there a way from the userAgent or runtime to detect it?

**Comment by bartoszboruta** [comment]
Hi @jdalton !
 Sorry for delay, found something like that:
`Mozilla/5.0 (Mobile; LYF/F90M/LYF-F90M-000-02-17-270917; rv:48.0) Gecko/48.0 Firefox/48.0 KAIOS/2.0`

**Comment by bartoszboruta** [comment]
@jdalton What about KaiIOS support? If that is not possible, close that issue please.
