### ISSUE TITLE
New release with security fixes

### ISSUE THREAD

**Issue by joaogarin** [bestiejs/platform.js#161]
Hello would it be possible to do a release with this commit https://github.com/bestiejs/platform.js/commit/f86e37437c155fb39253e5bcaa99e8cd265d5a12 that would be great! ;)  would fix some secutiry warnings in our repo

Thank you!

**Comment by jdalton** [comment]
\cc @bnjmnt4n

**Comment by bnjmnt4n** [comment]
Thanks for the ping - been slowly easing back into programming after being out of touch for a while. Will do the version bump by tonight and look at the rest of the issues over the next week.

**Comment by joaogarin** [comment]
Any news on when this could happen? 
Cheers

**Comment by jmtaillant** [comment]
Hello,
Any update on this?

**Comment by bnjmnt4n** [comment]
Just published [v1.3.6](https://github.com/bestiejs/platform.js/releases/tag/1.3.6) on npm. Realized that I forgot to update the version number in the readme, but apart from that everything has been tested thoroughly. Will update the changelog soon.
