### ISSUE TITLE
Platform1.3.5 : Microsoft Edge version is incorrect.

### ISSUE THREAD

**Issue by JDGHHou** [bestiejs/platform.js#162]
I am using MS Edge 41.16299.551.0, but platform reports it as 16.16299. It looks like maybe it's grabbing the first two digits of the minor version rather than reporting the proper major version?

**Comment by jdalton** [comment]
Hi @JDGHHou!

You're looking at the app shell version and not the platform version. The platform version (the lower one) is the one to pay attention to.
