### ISSUE TITLE
Avast Secure Browser on Windows is detected as Chrome

### ISSUE THREAD

**Issue by jacquesnys** [bestiejs/platform.js#166]
Avast Secure Browser not detected, Chrome detected instead

user agent:
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36 Avast/70.1.973.110

product info (extracted from help & about section):
executable_path=C:\Program Files (x86)\AVAST Software\Browser\Application\AvastBrowser.exe
profile_path=C:\Users\jacqu\AppData\Local\AVAST Software\Browser\User Data\Default
os_version=Windows 10 v1803 (x64) 
av_version=19.1
browser_version=70.1.973.110 (Developer Build a335cff6003e44ab63dbab2734092ca5514eed96- Windows)
cgid=111
cid=1116
uid=10fb49b36af64a2b867299e5608867eb

**Comment by jdalton** [comment]
Hi @jacquesnys!

We aren't trying to be super thorough here.
You might check out [`uap-core`](https://github.com/ua-parser/uap-core).
