### ISSUE TITLE
Add Sailfish OS and Sailfish Browser detection

### ISSUE THREAD

**Issue by rainemak** [bestiejs/platform.js#168]
User-agent will be updated:

> "Mozilla/5.0 (Linux; U; Sailfish 3.0; Mobile; rv:45.0) Gecko/45.0 Firefox/45.0 SailfishBrowser/1.0"

See sailfishos.org for more information about Sailfish OS.

**Comment by jdalton** [comment]
Hi @rainemak!

We aren't trying to be super thorough here.
You might check out [`uap-core`](https://github.com/ua-parser/uap-core).

**Comment by rainemak** [comment]
Hi @jdalton !

Thanks. Fixed in uap-core as well https://github.com/ua-parser/uap-core/pull/392
