### ISSUE TITLE
Microsoft Edge Preview support

### ISSUE THREAD

**Issue by augbog** [bestiejs/platform.js#172]
Microsoft is unveiling a new version of Edge that is based on Chromium.

https://www.microsoftedgeinsider.com/en-us/
https://blogs.windows.com/msedgedev/2019/04/08/microsoft-edge-preview-channel-details/

It looks like the expected user-agent string will be "**Edg**" to identify which may be confusing to a lot of users. I believe they may move forward with this and they say in the article the latest Dev Channel build has this as the UA string

```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.48 Safari/537.36 Edg/74.1.96.24
```

I wanted to put this suggestion sooner rather than later so it was on the radar. I'm not sure of the expectation of the `platform` package for this case?

**Comment by fdellwing** [comment]
See #170

**Comment by augbog** [comment]
Ah didn't know the codename was Anaheim which is why it didn't come up in my search. Will close as dupe. Thanks for triaging :)
