### ISSUE TITLE
Update NPM package

### ISSUE THREAD

**Issue by shayc** [bestiejs/platform.js#174]
Can you please update the [NPM package](https://www.npmjs.com/package/platform)?
It was last published 2 years ago but the GitHub repository was updated on July 2019.

There's a substantial improvement in the GitHub code, mainly detecting Edge Chromium.

Thanks ❤️

**Comment by samsiu** [comment]
See the commit history:
https://github.com/bestiejs/platform.js/commits/master

There is not much important feature upgrade since last publish

**Comment by bnjmnt4n** [comment]
Hey, sorry for the delay - will try to clear up some issues and bump this week.
