### ISSUE TITLE
Support iPadOS

### ISSUE THREAD

**Issue by shayc** [bestiejs/platform.js#175]
iPadOS is being detected as macOS, this was done by Apple to make [Safari behave more like a desktop version](https://forums.developer.apple.com/thread/119186).

So the only way that I know of to detect iPadOS is by checking for `maxTouchPoints` since Macs don't have touch screens (as of yet).

```js
 if (navigator.userAgent.match(/Mac/) && navigator.maxTouchPoints && navigator.maxTouchPoints > 2) {
     ...must be iPad OS...
```

Would you consider this a viable solution?

**Comment by r10s** [comment]
thanks for the hint, came over this while figuring out the same thing for delta chat (https://github.com/deltachat/deltachat-pages/issues/338) - seems to do the job :)

however, wondering, where the `navigator.maxTouchPoints > 2` comes from, `navigator.maxTouchPoints > 1` would sound more logical to me.

**Comment by shayc** [comment]
> however, wondering, where the `navigator.maxTouchPoints > 2` comes from, `navigator.maxTouchPoints > 1` would sound more logical to me.

I agree, I found the solution online, maybe these days people have a more intuitive one. All I remember is that it was hard to find something that works.

**Comment by r10s** [comment]
> half of my comments on GitHub are for people to find them in the future!

yeah! please keep on commenting :)
