### ISSUE TITLE
Most common values for platform.os.family not showing 'Linux' OS

### ISSUE THREAD

**Issue by rahulspace** [bestiejs/platform.js#177]
![Desktop screenshot](https://user-images.githubusercontent.com/34391727/74080824-0a6d1380-4a6e-11ea-8adb-a9a0067ce90f.png)

**Comment by bnjmnt4n** [comment]
I guess in reality, Linux is pretty uncommon as we detect the popular distros such as Ubuntu, Fedora, etc. first. Given that Linux is one of the major OS families, I've added it to the documentation.
