### ISSUE TITLE
support for microsoft edge chromium

### ISSUE THREAD

**Issue by sarfraz-akhtar** [bestiejs/platform.js#178]
microsoft edge released chromium edge, this library has missing support for chromium edge.
userAgent for chromium edge is different than old edge.
userAgent for chromium edge is:
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36 Edg/80.0.361.48"
it gives platform.name= "Chrome", but should provide "Edge".

**Comment by toschlog** [comment]
I fixed this problem by adding the line:
      { 'label': 'Microsoft Edge', 'pattern': 'Edg' },
right after the line:
      { 'label': 'Microsoft Edge', 'pattern': 'Edge' },
in Platform.js.

However, I don't know if that's the best long-term solution.

**Comment by born2net** [comment]
is this fix, showing Edge in label is released to latest build?

**Comment by toschlog** [comment]
I make my own build with the fix I described above.  It is not part of the source here.

**Comment by bnjmnt4n** [comment]
Hi, support for Chromium-based Edge versions was added in #170. I'll try to cleanup the rest of the issues and bugs and make a new release soon.
