### ISSUE TITLE
NW.js and Electron detection

### ISSUE THREAD

**Issue by dfcreative** [bestiejs/platform.js#18]
It would be nice to have a possibility to detect <a href="https://github.com/rogerwang/node-webkit">Node-Webkit</a>, as well as <a href="http://www.adobe.com/devnet/photoshop/scripting.html">Adobe ExtendScript</a>. There’s a lack of such lib for these platforms.

**Comment by lipis** [comment]
Maybe after 3 years.. it's about time to actually support this thing :)

**Comment by jdalton** [comment]
@lipis Create a PR.

**Comment by d10** [comment]
@lipis I haven’t had much time to maintain platform.js last year, but I’ll try to close up the rest of the issues by the end of January. PRs would be great though :)
