### ISSUE TITLE
Platform.name is not detecting firefox in iPad

### ISSUE THREAD

**Issue by sarthak4allworks** [bestiejs/platform.js#189]
platform.name is returning Safari when I run my application on Firefox of iPad.

**Comment by sarthak4allworks** [comment]
iPad 6th generation with software version 14.2(18B92)
On printing the navigator.userAgent I am getting the following messages
Safari: Mozilla/5.0 (Machintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15
Firefox: Mozilla/5.0 (Machintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15
Chrome: (iPad; CPU OS 14_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CricOS/87.0.4280.77 Mobile/15E148 Safari/604.1.1
 
because of this I am not able to identify Firefox browser.
Is there any other way to detect Firefox in iPad.

**Comment by bnjmnt4n** [comment]
Since it appears that Firefox on iPad does not provide any distinguishing feature in its user-agent, we would be unable to differentiate between Safari and Firefox.
