### ISSUE TITLE
Will platform.js work for Chrome or Firefox versions greater than 100??

### ISSUE THREAD

**Issue by surya04pratap** [bestiejs/platform.js#200]

**Comment by moefinley** [comment]
I'm looking for the answer to this too.
For context https://www.theverge.com/2022/2/17/22938721/chrome-firefox-edge-version-100-websites-bug-compatibility-issues-mozilla-google-microsoft

**Comment by naXa777** [comment]
works fine for me
![image](https://user-images.githubusercontent.com/3858548/183421034-515dc768-005f-432b-85df-cb7d665928a0.png)

demo page for testing 
https://bestiejs.github.io/platform.js/
