### ISSUE TITLE
Documentation of most common values for platform.os.family

### ISSUE THREAD

**Issue by eliotsykes** [bestiejs/platform.js#55]
Thanks for platform.js. Are the most common values for platform.os.family listed in the docs? I was unable to find if it is there, and in that case I'm sorry for opening this issue. If it isn't in the docs, I think this would be a useful addition.

**UPDATE 27th May 2014**
I'll keep this table updated as new ones are added. Please go to http://jsfiddle.net/bGyNa/4/embedded/result/ to contribute your platform.os.family value if its not yet mentioned in the table:

| platform.os.family |
| --- |
| OS X |
| Android |
| iOS |

_Table last updated: 27th May 2014_
_platform.js version 1.1.0_

**Comment by rahulspace** [comment]
Linux
