### ISSUE TITLE
IE 11 Enterprise Mode

### ISSUE THREAD

**Issue by JakeSummers** [bestiejs/platform.js#74]
It looks like `platform.js` can detect IE compatability mode.  Is it able to detect [IE11 enterprise mode](http://msdn.microsoft.com/en-us/library/dn640687.aspx)?  Any plans to add detection of this?  

I searched the repo for 'enterprise', but didn't see anything.

**Comment by d10** [comment]
I’m not too sure if there is anyway to detect Enterprise mode. @jdalton?

**Comment by jdalton** [comment]
I'm sure there is. The point is for it to more closely simulate IE8 than previous compatibility modes. I'll poke around a bit. @JakeSummers why are you wanting to detect it?

**Comment by JakeSummers** [comment]
@jdalton - I am wanting to detect it largely so I can ask my users to turn it off.  They potentially have a great browser (IE11) but it is running in a bad mode (IE8).

**Comment by jdalton** [comment]
I don't think you have to worry about users accidentally being in enterprise mode as it requires admins to add their own list of websites to load in Enterprise Mode and the menu option is hidden by default.
