### ISSUE TITLE
No os.family reported for Chrome on HP Chromebook

### ISSUE THREAD

**Issue by dotherightthing** [bestiejs/platform.js#77]
{
            "description":"Chrome 40.0.2214.93",
            "layout":"Blink",
            "manufacturer":null,
            "name":"Chrome",
            "prerelease":null,
            "product":null,
            "ua":"Mozilla/5.0 (X11; CrOS armv7l 6457.83.0) AppleWebKit/537.36 (KHTML,like Gecko) Chrome/40.0.2214.93 Safari/537.36",
            "version":"40.0.2214.93",
            "os":{
                "architecture":null,
                "family":null,
                "version":null
            }
        }

Is this expected?

Thanks.

**Comment by d10** [comment]
Currently, we haven’t added support for Chrome OS (totally forgot about it). We’ll add that in soon.

**Comment by dotherightthing** [comment]
@d10 Thanks, good stuff.

**Comment by danopia** [comment]
Just here for a :+1: on this issue, I assumed the library wasn't working because I develop on a Chromebook

```{
   "description":"Chrome 43.0.2357.46",
   "layout":"Blink",
   "manufacturer":null,
   "name":"Chrome",
   "prerelease":null,
   "product":null,
   "ua":"Mozilla/5.0 (X11; CrOS x86_64 6946.31.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.46 Safari/537.36",
   "version":"43.0.2357.46",
   "os":{
      "architecture":null,
      "family":null,
      "version":null
   }
}```

**Comment by mhulse** [comment]
+1 :octocat:

**Comment by benawhite** [comment]
+1 also :)
