### ISSUE TITLE
os type

### ISSUE THREAD

**Issue by acthp** [bestiejs/platform.js#78]
Having os family "Red Hat", "Suse", "Linux Mint" etc., is probably not useful to many developers. In most cases when code needs to know about os, it needs to know linux/windows/osx. It could be useful to add a more general os type to capture this.

**Comment by d10** [comment]
@jdalton any opinions on this? I'm not too good with API design kind of stuff ;)

**Comment by jdalton** [comment]
>  In most cases when code needs to know about os, it needs to know linux/windows/osx. 

See the [disclaimer](https://github.com/bestiejs/platform.js#disclaimer). Platform.js gets its info from the UA and the environment I'd prefer keeping it simple.

**Comment by acthp** [comment]
Feature detection is really a different issue, unless you count "can execute binaries compiled for intel 64 bit OSX" to be a feature. ;)  The use cases are about delivering services, executables, etc. that are specific to os; not about trying to build dbs of browser features indexed by os, which would be better done by feature detection. But I understand about wanting to keep it simple.

I haven't found a standard lib for this. It appears every site invents their own partially complete set of patterns.
