### ISSUE TITLE
Spartan is captured as IE12

### ISSUE THREAD

**Issue by hkyip** [bestiejs/platform.js#79]
Spartan is captured as IE12. Is it a desire behaviour?

**Comment by jdalton** [comment]
We should name it "Microsoft Edge" now that the name is official.

**Comment by hkyip** [comment]
+1

**Comment by am11** [comment]
x-ref: https://github.com/jsperf/jsperf.com/issues/36.

**Comment by pindiespace** [comment]
Edge detected as IE 13 on most recent Windows (12/20/2015) upgrade.

"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586"

**Comment by jdalton** [comment]
Patched #86. I don't believe it's been npm published though.

**Comment by pindiespace** [comment]
yes, I was using the npm
