### ISSUE TITLE
Can we distinguish between 64 bit chrome and 32 bit chrome?

### ISSUE THREAD

**Issue by toastkid** [bestiejs/platform.js#80]
There's an entry in the changelog - "Fixed detection of 64-bit Chrome running on Windows" - which suggests this may be possible, but i can't see how looking at what i get back in `platform`.  thanks

**Comment by jdalton** [comment]
It depends. Platform looks for hints [from the UA string](https://github.com/bestiejs/platform.js/blob/fcb23d1ac56a5ea3115e3d972051ea33a8baf22b/platform.js#L960-L972) and the environment.

**Comment by toastkid** [comment]
If it's just the userAgent string i don't think that's going to work - very annoyingly, userAgent doesn't include the "(64 bit)" which appears after the version when you view it on the About page.  I'd seen that you were analysing the userAgent string but hoped that there was some other magic going on which i'd missed!  Thanks a lot for answering my issue.
