### ISSUE TITLE
Missing browsers

### ISSUE THREAD

**Issue by jbardu** [bestiejs/platform.js#82]
PaleMoon
Waterfox
SamsungBrowser
AOL
UCBrowser (popular in Japan)
YaBrowser (popular in Russia)
Mobile Safari under Facebook (... FBAN and FBSV)
Tesla (QtCarBrowser)

Missing OS

SCO_VS
OpenBSD
Tesla (Linux variant)

If you want to add these do you need me to post the user-agents?

**Comment by wolfbeast** [comment]
General UA of Pale Moon:
`Mozilla/5.0 ({OS}; {Arch}; rv:{PM version}) Gecko/{BuildID} PaleMoon/{PM version}`

e.g.: Pale Moon 25.* (x86 on on windows 7 x64) has a UA of:
`Mozilla/5.0 (Windows NT 6.1; WOW64; rv:25.8) Gecko/20151116 PaleMoon/25.8.0`
or (firefox compatmode)
`Mozilla/5.0 (Windows NT 6.1; WOW64; rv:25.8) Gecko/20151116 Firefox/31.9 PaleMoon/25.8.0`
Other OS/Arch combinations are like Firefox.

Information about Pale Moon compatibility for UA sniffers can be found here for the upcoming Goanna-based version 26:
https://forum.palemoon.org/viewtopic.php?f=24&t=9077

**Comment by jdalton** [comment]
The goal isn't to get all browsers, because there are tons of small one off ones. If you have usage stats that may help us filter out which ones would be worth supporting.

**Comment by wolfbeast** [comment]
Pale Moon currently has over half a million users (global browser usage stats concur and put it slightly above SeaMonkey percentage-wise) and growing. It's not a one-off one (been running for 6 years) and here to stay. If you'd give it some consideration, then that would be great! :smile:

**Comment by jdalton** [comment]
Do you have a link?

**Comment by wolfbeast** [comment]
To the browser website? http://www.palemoon.org/

If you meant to the stats, then you can find our last "best guess" (since we don't collect telemetry) in this thread: https://forum.palemoon.org/viewtopic.php?f=4&t=8801&p=58463#p59137 which is from July (and it's been clearly growing pretty fast since then, going by server load).

As for global stats, I can't really find the specific post right now, but it was a pleasant surprise when seeing it had actually passed SM (albeit by a small margin); that too was a while back, I gather the gap has gotten quite a bit bigger by now.

**Comment by rodneyrehm** [comment]
Here's the output of platform.js v1.3.0 for two arguably relevant browsers on Android that both identify as "Android Browser":

[UC Browser](https://play.google.com/store/apps/details?id=com.UCMobile.intl&hl=en) (100mio - 500mio installs)

```json
{
  "description": "Android Browser 4.0 (like Safari 5.x) on Android 5.1",
  "layout": "WebKit",
  "manufacturer": null,
  "name": "Android Browser",
  "prerelease": null,
  "product": null,
  "ua": "Mozilla/5.0 (Linux; U; Android 5.1; en-US; XT1021 Build/LPC23.13-34.8) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 UCBrowser/10.7.5.658 U3/0.8.0 Mobile Safari/534.30",
  "version": "4.0",
  "os": {
    "architecture": 32,
    "family": "Android",
    "version": "5.1"
  }
}
```

[Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox&hl=en) (100mio - 500mio installs)

```json
{
  "description": "Android Browser 43.0 (Gecko) on Android 5.1",
  "layout": "Gecko",
  "manufacturer": null,
  "name": "Android Browser",
  "prerelease": null,
  "product": null,
  "ua": "Mozilla/5.0 (Android 5.1; Mobile; rv:43.0) Gecko/43.0 Firefox/43.0",
  "version": "43.0",
  "os": {
    "architecture": 32,
    "family": "Android",
    "version": "5.1"
  }
}
```

**Comment by jdalton** [comment]
Thanks!

**Comment by d10** [comment]
I’ll look into this ASAP. We currently haven’t added UC Browser to our lists of browsers, however Firefox for Android should be there. I’ll try to see what’s wrong with our Firefox code.

**Comment by d10** [comment]
The issue with Firefox Mobile seems to be due to [a change in the UA string](https://bugzilla.mozilla.org/show_bug.cgi?id=1169772). /cc @miketaylr

I’m currently working on a fix for that.

**Comment by miketaylr** [comment]
Guilty as charged... thanks for fixing! :+1:

**Comment by JonathanMH** [comment]
First of all, thank you for this awesome module!
I found a missing one too, that seems to be an Apple Safari:

String: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/600.8.9 (KHTML, like Gecko)`

output:
```
{ description: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/600.8.9 (KHTML, like Gecko)',
  layout: 'WebKit',
  manufacturer: null,
  name: null,
  prerelease: null,
  product: null,
  ua: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/600.8.9 (KHTML, like Gecko)',
  version: null,
  os: 
   { architecture: 32,
     family: 'OS X',
     version: '10.10.5',
     toString: [Function] },
  parse: [Function: parse],
  toString: [Function: toStringPlatform] }
```

source: https://user-agents.me/browser/mozilla50-macintosh-intel-mac-os-x-10_10_5-applewebkit60089-khtml-like-gecko-version808-safari60089

**Comment by rodneyrehm** [comment]
[Yandex Browser](https://browser.yandex.com/) is wrongly identified as Chrome:

```js
{
  "description": "Chrome 41.0.2272.118β on OS X 10.10.5",
  "layout": "Blink",
  "manufacturer": null,
  "name": "Chrome",
  "prerelease": "beta",
  "product": null,
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 YaBrowser/15.4.2272.3909 (beta) Yowser/2.0 Safari/537.36",
  "version": "41.0.2272.118β",
  "os": {
    "architecture": 32,
    "family": "OS X",
    "version": "10.10.5"
  }
}
```

The relevant component seems to be `YaBrowser/15.4.2272.3909 (beta)`.
According to statcounter.com this browser has ~12% marketshare in Russia.
`window.chrome` and `window.yandex` are set.

**Comment by jeffrose** [comment]
Unless I overlooked it I did not see support for [SlimerJS](https://slimerjs.org/) either.

```Mozilla/5.0 (X11; Linux x86_64; rv:21.0) Gecko/20100101 SlimerJS/0.7```

**Comment by jdalton** [comment]
Closing as stale and semi resolved.
