### ISSUE TITLE
Add desktop, tablet, mobile boolean detection

### ISSUE THREAD

**Issue by swannknani** [bestiejs/platform.js#84]
Is there a way to add a platform object property like so instead of test all ```platform.product```

// Tablet

```platform.desktop = false;```
```platform.tablet = true;```
```platform.mobile = false;```

**Comment by d10** [comment]
I don’t think this would be very feasible, as there are many devices out there, and it would be difficult to account for each different kind of product. Also there is no clear distinction between different kinds of devices with the rise of different form factors for devices (eg. phablets).

**Comment by heff** [comment]
It seems like some best guesses could be made without knowing all of the devices.
https://developer.mozilla.org/en-US/docs/Browser_detection_using_the_user_agent#Mobile.2C_Tablet_or_Desktop
