### ISSUE TITLE
Incorrect Chrome version detection

### ISSUE THREAD

**Issue by AshwiniMD** [bestiejs/platform.js#85]
The version of Chrome is incorrect.

E.g Run the test by adding following user agent node to test.js -
'Chrome 40.0.2214.89 on (Android 5.1.1)': {
      'ua': 'Mozilla/5.0 (Linux; Android 5.1.1; SGP521 Build/23.4.A.0.546) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/40.0.2214.89 Safari/537.36',
      'layout': 'Blink',
      'name': 'Chrome',
      'os': 'Android 5.1.1,
      'version': '40.0.2214.89'
    }
Result: Detects version as 4.0.0 instead of 40.0.2214.89.
Screeshot of the test output: 
<img width="1435" alt="screen shot 2015-07-24 at 11 55 58 am" src="https://cloud.githubusercontent.com/assets/3282241/8873117/0437c3cc-320c-11e5-8fa8-9a0b4c5fd4c4.png">

**Comment by d10** [comment]
Argh, this is a never ending issue. The reason for inaccurate detection is that some stock Android browsers identify as Chrome, and we have to filter out those from real Chrome on Android. The Chrome UA seems to have changed though IIRC, which caused this issue.

**Comment by AshwiniMD** [comment]
Hi,

Can we update the Chrome UA to new one in this case?

**Comment by d10** [comment]
Sorry for the late reply, but, to clarify: was the user agent from Chrome on Android or the default Android browser?

**Comment by swapneeldesai** [comment]
The user agent is from Chrome on Android.

**Comment by mimmi20** [comment]
@d10 As you can see here (https://developer.chrome.com/multidevice/user-agent#webview_user_agent) the useragent is not from Chrome, but from the Chrome based Android WebView.

**Comment by d10** [comment]
@mimmi20 Thanks for the heads up, I’ve looked into the Chrome based WebViews before but haven’t had the time to add detection. This would probably also have some conflicts with the current stock Android browser detection, as some stock Android browsers include both the `Version` and `Chrome` tags.
