### ISSUE TITLE
Windows 7 Professional is recognized as Windows Server 8

### ISSUE THREAD

**Issue by wackazong** [bestiejs/platform.js#88]

**Comment by d10** [comment]
Windows 7 has the same token as Windows 2008 Server, so there is no easy way to differentiate between the two operating systems. Currently we mark it up as `"Windows Server 2008 R2 / 7"` to show that it could be either.

**Comment by jdalton** [comment]
We should lead with Windows 7, so `Windows 7 / Server 2008 R2`.
