### ISSUE TITLE
Pale Moon errors on platform.js (b.name is null)

### ISSUE THREAD

**Issue by wolfbeast** [bestiejs/platform.js#90]
platform.js is used as part of the www.chase.com website in a "polyfill to remove click delays on browsers with touch UIs" which led me to this repo.

Apparently, the script chokes on the particular combination of available JS functions in Pale Moon and throws a "TypeError: b.name is null". Since the script is minified on that site, I can't provide any more particulars as it's all stuffed in a single line.

**Comment by jdalton** [comment]
Related to #82.

**Comment by d10** [comment]
This isn’t an error on our part, seems that the polyfill you use doesn’t account for the fact that [`platform.name`](https://github.com/bestiejs/platform.js/blob/1.3.1/doc/README.md#platformname) could be `null`. (Although we will probably add PaleMoon as a browser soon.)

**Comment by wolfbeast** [comment]
I don't have any more details about the polyfill since I didn't author the website. I landed here because the website is problematic and is obviously using your platform module. The polyfill is also minified so reverse-engineering it is problematic. I've tried to get a hold of the right people at Chase but you may have more luck considering they are actively using your code (while they may not actively be supporting our browser).
