### ISSUE TITLE
What to rename toString() method?

### ISSUE THREAD

**Issue by xurban42** [bestiejs/platform.js#95]
I made one fail. I was calling toString like  

```javascript
platformJS.parse(<myuseragentstring>).os.toString()
```

And it doesn't work - I was getting `"[object Object]"` string.

It was  because [https://developer.mozilla.org/cs/docs/Web/JavaScript/Reference/Global_Objects/Object/toString] was called instead.

I think renaming of this method could help.

**Comment by jdalton** [comment]
I can't repro the issue.
```js
platform.parse(navigator.userAgent).os.toString()
// => "OS X 10.11.2"
```
