### ISSUE TITLE
platform.os.architecture returns incorrect value on chrome Mac OSX

### ISSUE THREAD

**Issue by alechewitt** [bestiejs/platform.js#97]
`platform.os.architecture`
returns
`32`

but yet I am running a 64 bit version of Chrome on MacOSX.

The UA string is:
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36`

and navigator.platform returns:
`MacIntel`

The only way I can seem to determine it is a 64 bit version of chrome is by viewing the chrome version information:
<img width="460" alt="screen shot 2016-03-21 at 17 57 26" src="https://cloud.githubusercontent.com/assets/4737140/13912178/6d6bba16-ef8e-11e5-8d0e-36d9c9440c8d.png">

**Comment by jdalton** [comment]
If all Intel Macs are 64 bit then that's a good way to detect it.

**Comment by alechewitt** [comment]
Yes it seems Chrome stopped supporting 32bit Mac machines back in 2014 http://www.omgchrome.com/chrome-32-bit-mac-discontinued-later-year/[http://www.omgchrome.com/chrome-32-bit-mac-discontinued-later-year/](url)

**Comment by jdalton** [comment]
Moving to #98.
