### ISSUE TITLE
Support EOL

### ISSUE THREAD

**Issue by dodekeract** [bestiejs/platform.js#99]
Would be nice if this module could give you information about whether or not `CRLF` is needed.

**Comment by mathiasbynens** [comment]
What?

**Comment by dodekeract** [comment]
@mathiasbynens Windows (and maybe other operating systems) are using Carriage Return Line Feeds to end their lines. Linux and Mac (and maybe other operating systems) are using Line Feed to end a line.

This would be useful for my particular use-case to know which one I have to use, based on the platform.

**Comment by jdalton** [comment]
I think that's a bit out of scope of this project. It's tackled by Node through `require('os').EOL`.
